# fly.toml app configuration file generated for personal-tomo-start on 2023-11-03T12:03:41Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "personal-tomo-start"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
